"""Updating models with new foreign key relationships.

Revision ID: 359c1b2af6c9
Revises: aad4194fd9b0
Create Date: 2023-11-16 20:05:44.942453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359c1b2af6c9'
down_revision = 'aad4194fd9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('park_amenities', schema=None) as batch_op:
        batch_op.drop_index('ix_park_amenities_amenity_id')
        batch_op.create_index(batch_op.f('ix_park_amenities_amenity_id'), ['amenity_id'], unique=False)

    with op.batch_alter_table('parks', schema=None) as batch_op:
        batch_op.drop_column('nps_url')
        batch_op.drop_column('access_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('nps_url', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('park_amenities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_park_amenities_amenity_id'))
        batch_op.create_index('ix_park_amenities_amenity_id', ['amenity_id'], unique=False)

    # ### end Alembic commands ###
