"""Create 'park_amenities' table.

Revision ID: 4f704148febd
Revises: f708f0a038da
Create Date: 2023-04-07 08:51:50.824923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f704148febd'
down_revision = 'f708f0a038da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('park_amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('amenity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name=op.f('fk_park_amenities_amenity_id_amenities')),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_park_amenities_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('park_amenities')
    # ### end Alembic commands ###
