"""Add ParkingLot model, update relationships.

Revision ID: 5dc1c2b58be1
Revises: 359c1b2af6c9
Create Date: 2023-11-16 20:50:38.903024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc1c2b58be1'
down_revision = '359c1b2af6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('park_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gen_description', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_spaces', sa.Integer(), nullable=True),
    sa.Column('total_ada_spaces', sa.Integer(), nullable=True),
    sa.Column('van_accessible_spaces', sa.Integer(), nullable=True),
    sa.Column('step_free_spaces', sa.Integer(), nullable=True),
    sa.Column('oversize_vehicle_spaces', sa.Integer(), nullable=True),
    sa.Column('ada_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['park_code'], ['parks.code'], name=op.f('fk_parking_lots_park_code_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('park_amenities', schema=None) as batch_op:
        batch_op.drop_index('ix_park_amenities_amenity_id')
        batch_op.create_index(batch_op.f('ix_park_amenities_amenity_id'), ['amenity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('park_amenities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_park_amenities_amenity_id'))
        batch_op.create_index('ix_park_amenities_amenity_id', ['amenity_id'], unique=False)

    op.drop_table('parking_lots')
    # ### end Alembic commands ###
