"""Add amenity_id indexing.

Revision ID: 8921fabb7728
Revises: 64a3c5edba1f
Create Date: 2023-05-15 12:55:26.917732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8921fabb7728'
down_revision = '64a3c5edba1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('park_amenities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_park_amenities_amenity_id'), ['amenity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('park_amenities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_park_amenities_amenity_id'))

    # ### end Alembic commands ###
