"""Create 'parks' table.

Revision ID: f708f0a038da
Revises: 22ed36ad201e
Create Date: 2023-04-06 12:09:04.995094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f708f0a038da'
down_revision = '22ed36ad201e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nps_api_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('states', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('image_alt', sa.String(), nullable=True),
    sa.Column('image_credit', sa.String(), nullable=True),
    sa.Column('weather', sa.String(), nullable=True),
    sa.Column('nps_url', sa.String(), nullable=True),
    sa.Column('access_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parks')
    # ### end Alembic commands ###
